На пути к совершенству
htmlacademy-yii/598165-task-force-1 pull request #5
Opened 2020-01-19 07:46 UTC by surikov-k

2020-01-24 04:36 UTC, nkolosov requested changes

2020-01-24 04:36 UTC, nkolosov commented on src/models/AbstractAction.php
> +    public function getInternalName()
Не хватает type hint и phpDoc

2020-01-24 04:36 UTC, nkolosov commented on src/models/Task.php
> +        $this->actions = [
Лучше получение `actions` и `transitions` вынести в отдельные статические методы, так как нет смысла их инициализировать для каждого объекта

2020-01-26 16:07 UTC, nkolosov requested changes

2020-01-26 16:07 UTC, nkolosov commented on src/models/AbstractAction.php
> +namespace TaskForce\models;
Все `actions` стоит вынести в отдельный namespace

2020-01-26 16:07 UTC, nkolosov commented on src/models/FinishAction.php
> +        return $user->id === $task->client->id;
У задания нет свойств `client` и `contractor`, код работать не будет

2020-01-26 16:07 UTC, nkolosov commented on src/models/Strategy.php
> +    public function __construct(int $clientId, ?User $contractor)
Странно, что заказчик передается в виде id, а исполнитель - объектом. Стоит сделать единообразно

2020-01-26 16:07 UTC, nkolosov commented on src/models/Task.php
> +    private function actions()
Метод всегда возвращает одно и тоже, стоит его сделать статическим (и добавить type hint везде)

2020-03-05 23:51 UTC, surikov-k commented on src/models/Task.php
> +    private function actions()
В методе же используются поля экземпляра?

2020-03-07 09:37 UTC, nkolosov approved these changes

2020-03-07 09:37 UTC, merged